### ISSUE TITLE
[suggestion] Provide link to fp-ts guide on do notation

### ISSUE THREAD

**Issue by kmbt** [inato/fp-ts-cheatsheet#18]
First of all, I would like to thank you for posting this cheat sheet! It's been really useful for me as a reference.

What I have noticed, is that the guide does not give much info on the Do Notation. It is only briefly shown without much explanation in the last paragraph: https://github.com/inato/fp-ts-cheatsheet#-call-in-parallel

I think that it would be useful to have more details on the Do Notation, and this could be easily achieved by putting there a link to this page: https://gcanti.github.io/fp-ts/guides/do-notation.html

What do you think?

**Comment by vinassefranche** [comment]
Thanks for the suggestion @kmbt 
I've opened the P.R. for that.
